### ISSUE TITLE
Just why?

### ISSUE THREAD

**Issue by gamingdiamond982** [MrNavaStar/EasyEula#2]
why would someone go to the hassle of installing a mod instead of just opening a file and changing false to true?

like neither involve much effort, but that has to be so much slower.

**Comment by MrNavaStar** [comment]
Thanks for asking, This mod is not intended for server owners. It is aimed at developers who do server side dev. You can add this mod to your development environment (via build.gradle) and then anywhere your environment is spun up, you wont need to deal with eulas. Again this is not intended for server owners, as yes that makes no sense. Please see the readme.

**Comment by gamingdiamond982** [comment]
That was pretty snarky of me, sorry.
The idea seems really neat, and in my limited experience with mod development seems pretty handy.

Cheers for the kind and genuine response.
